### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by utranhost** [atticus-lv/LightLinkingPanel#3]
<img width="525" alt="Snipaste_2024-12-24_16-50-38" src="https://github.com/user-attachments/assets/9febac18-b94e-41b7-9bf3-987ba5e196f0" />
复现bug,随意导入一个fbx文件，大纲视图 - blender文件 -> 删除所有材质。此后”灯光链接“那一栏就不再可用了。

**Comment by nurb2kea** [comment]
After update this morning. light link not available to intitiate.
Latest MacOS , latest blender 4.4
It was working yesterday with blender 4.4

Python: Traceback (most recent call last):
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/panel.py", line 169, in draw
    self.draw_light_list(context, layout)
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/panel.py", line 267, in draw_light_list
    icon, _ = LLP_OT_switch_filter_show.get_icon(context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/ops.py", line 385, in get_icon
    for obj in filter_objects(context):
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/filter.py", line 38, in filter_objects
    for i, v in enumerate(filter_list(context, bitflag=True)):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/filter.py", line 18, in filter_list
    is_show = obj.type == "LIGHT" or check_material_including_emission(obj)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/utils.py", line 327, in check_material_including_emission
    return node_tree_search(out_node) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/utils.py", line 310, in node_tree_search
    find = node_tree_search(from_node, depth + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/utils.py", line 320, in node_tree_search
    return node_tree_search(input_point.node_tree, depth + 1)
                            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NodeSocketFloatFactor' object has no attribute 'node_tree'

![Screenshot 2024-12-24 at 12 25 35 pm](https://github.com/user-attachments/assets/021b5c9c-7e19-4a23-b864-98692e94adca)

**Comment by nurb2kea** [comment]
Thanks that fixed the issue in blender 4.4 as you can see in the images. I replaced the utils.py with your updated one.

One thing I realised is: when using meshlights, they only get recognised when the emission is direct attached to the output node. When ther is a mix node between, it won't show up in the addon panel.
Means that most addons offering meshlights doesn't show up in the panel & all mesh lights using nodegroups for the emission material that come as assets.
So vanilla blender can see and use this meshlights.
(my startup.blend contains 3 meshlights and I was wondering why they don't appear in the list. I think I could see the meshlights in a former version of your addon...!?)

Thanks for fixing stuff at this time of the year. With this issue here don't worry, there is no rush since the rest works fine so far.
So have some rest the next days if you celebrate!

Thanks in advance

![Screenshot 2024-12-25 at 12 37 29 am](https://github.com/user-attachments/assets/24d1c37f-f3a8-43fa-b089-6a0e28a4d094)

some examples for meshlight node setups coming with lighting addons and such:
![Screenshot 2024-12-25 at 12 42 43 am](https://github.com/user-attachments/assets/f44ce947-b94b-4617-8465-c1c6b7d9e417)

**Comment by xmx-emm** [comment]
> some examples for meshlight node setups coming with lighting addons and such: ![Screenshot 2024-12-25 at 12 42 43 am](https://private-user-images.githubusercontent.com/57676085/398489662-f44ce947-b94b-4617-8465-c1c6b7d9e417.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTczNTcsIm5iZiI6MTczNTA5NzA1NywicGF0aCI6Ii81NzY3NjA4NS8zOTg0ODk2NjItZjQ0Y2U5NDctYjk0Yi00NjE3LTg0NjUtYzFjNmI3ZDllNDE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAzMjQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMTMyZTFjYzA0MjhjZjQ4YTlmNDcyZDdiNWEwNmJlMjBlZGEwODA0MTM4NmJkZmUxNjM3YTVjNDcyM2JlY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rG2ZTAUR2EzRKBlSG6ODXicjkEUxgMGOkjMI9MFp-aY)

Need to provide unrecognized files
There is currently no search for self luminous nodes within the node group

**Comment by xmx-emm** [comment]
This bug has been fixed. If there are any other issues, you can open a new issue

[v0.3.7](https://github.com/AIGODLIKE/LightHelper/releases/tag/v0.3.7)

**Comment by xmx-emm** [comment]
@nurb2kea 
Node groups are already supported. If there are any other issues, please create a new one
[v0.3.8](https://github.com/AIGODLIKE/LightHelper/releases/tag/v0.3.8)

**Comment by nurb2kea** [comment]
"" Node groups are already supported. If there are any other issues, please create a new one
[v0.3.8](https://github.com/AIGODLIKE/LightHelper/releases/tag/v0.3.8) ""

I don't understand this answer!?
In your first answer you say: "There is currently no search for self luminous nodes within the node group" and then tha it has been fixed with 0.3.7. Then comes the last answer that nodegroups are already supported and version 0.3.8...

What does that mean.?
 I tested 0.3.8 and my issues are fixed except with the meshlights detection and appearing in the addon panel list.
Attached a startup file with 6 lights in it. 3 mesh and 3 normal lights.
Only the normal light come up. the mesh lights don't !
https://drive.google.com/open?id=1qzjLtwqQbi4vsF9UlQykEd2Qe_Jf_Q8o

For Info:
Here you see all the lights listed in photographer. With photographer addon you hit a button to search for emmisive lights, and it finds it and puts it into the list.
![Screenshot 2024-12-25 at 7 23 00 am](https://github.com/user-attachments/assets/63cb12c6-9d25-4237-bba2-abce1f848a7f)

**Comment by xmx-emm** [comment]
Maybe we should try this version

[v0.3.9](https://github.com/AIGODLIKE/LightHelper/releases/tag/v0.3.9)

**Comment by nurb2kea** [comment]
Looking good. I'll test more later today.
Thank you very much.
Pretty awesome support !!

![Screenshot 2024-12-25 at 10 43 37 am](https://github.com/user-attachments/assets/10f69562-b569-4751-95c1-d53aaf749511)
